<a href="https://colab.research.google.com/github/alibagheribardi/Regression/blob/main/saleh_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from scipy.linalg import block_diag
import matplotlib.pyplot as plt


N=13


w = np.exp((2j * np.pi) / N)

F = (1 / np.sqrt(N)) * np.exp((-2j * np.pi / N) * np.outer(np.arange(N), np.arange(N)))


# Construct matrices
J = np.eye(N - 1)[::-1]
JJ = block_diag(np.ones(1), J)
I = np.eye(N)

# Compute projection matrices
P_plus1 = (1/4) * (I + JJ) + (1/4) * (I + JJ) @ F
P_minus1 = (1/4) * (I + JJ) - (1/4) * (I + JJ) @ F
P_plusi = (1/4) * (I - JJ) - 1j * (1/4) * (I - JJ) @ F
P_minusi = (1/4) * (I - JJ) + 1j * (1/4) * (I - JJ) @ F

# Extract eigenvectors
m = (N - 1) // 4
V_plus1 = P_plus1[:, :m+1]
V_minus1 = P_minus1[:, :m]
V_plusi = P_plusi[:, 1:m+1]
V_minusi = P_minusi[:, 1:m+1]


eigvecs_fourier = np.hstack([V_plus1, V_minus1, V_plusi, V_minusi])

result = np.linalg.inv(eigvecs_fourier) @ F  @ eigvecs_fourier
real = np.round( np.real(result) ,2 )
image =np.round( np.imag(result) ,2 )
Fourier_check = real + 1j* image

array([[ 1.+0.j,  0.+0.j, -0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,
         0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  1.+0.j,  0.+0.j, -0.+0.j, -0.+0.j,  0.+0.j,  0.+0.j,
         0.+0.j,  0.+0.j,  0.+0.j, -0.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j, -0.+0.j,  1.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,
         0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j, -0.+0.j, -0.+0.j],
       [ 0.+0.j, -0.+0.j,  0.+0.j,  1.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,
         0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j, -0.+0.j],
       [ 0.+0.j,  0.+0.j, -0.+0.j,  0.+0.j, -1.+0.j, -0.+0.j,  0.+0.j,
         0.+0.j,  0.+0.j, -0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j, -0.+0.j,  0.+0.j,  0.+0.j, -1.+0.j,  0.+0.j,
         0.+0.j,  0.+0.j, -0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j, -0.+0.j,  0.+0.j,  0.+0.j, -0.+0.j, -1.+0.j,
        -0.+0.j,  0.+0.j, -0.+0.j, -0.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j, 

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

m=(N-1) // 2

G = (1 / np.sqrt(N)) * np.exp((-2j * np.pi / N) * np.outer(np.arange(N)+0.5, np.arange(N)+0.5))
G4= np.linalg.matrix_power(G,4)
real = np.round( np.real(G4) ,2 )
image =np.round( np.imag(G4) ,2 )
check_G4 = real +1j*image
check_G4



k = np.arange(m)
l = np.arange(m)
angles = ((2 * k[:, None] + 1) * (2 * l + 1) * np.pi) / (2 * N)
C = (2 / np.sqrt(N)) * np.cos(angles)

check_C2 = np.round( (C@C) ,2 )
check_C2


k = np.arange(m + 1)
l = np.arange(m + 1)
angles = ((2 * k[:, None] + 1) * (2 * l + 1) * np.pi) / (2 * N)
S = (2 / np.sqrt(N)) * np.sin(angles)

check_S2 = np.round( (S@S) ,2 )
check_S2


array([[ 1.15, -0.15,  0.15, -0.15,  0.15, -0.15,  0.15],
       [-0.15,  1.15, -0.15,  0.15, -0.15,  0.15, -0.15],
       [ 0.15, -0.15,  1.15, -0.15,  0.15, -0.15,  0.15],
       [-0.15,  0.15, -0.15,  1.15, -0.15,  0.15, -0.15],
       [ 0.15, -0.15,  0.15, -0.15,  1.15, -0.15,  0.15],
       [-0.15,  0.15, -0.15,  0.15, -0.15,  1.15, -0.15],
       [ 0.15, -0.15,  0.15, -0.15,  0.15, -0.15,  2.15]])

In [ ]:
I = np.eye(m)
C_p = C + I
C_m = C - I

p=m//2
v_i = C_p[:, 0:p]
u_i = C_m[:, 0:p]

J = np.eye(m)[::-1]
J_v_i = J @ v_i
J_u_i = J @ u_i

zero = np.zeros((1, p))
eigvec1 = np.concatenate([v_i, zero, -J_v_i], axis=0)
eigevec_minues1 = np.concatenate([u_i, zero, -J_u_i], axis=0)


check_1 = G @ eigvec1 -eigvec1
real = np.round( np.real(check) ,2 )
image =np.round( np.imag(check) ,2 )
real + 1j* image

check_minues1 = G @ eigevec_minues1  + eigevec_minues1
real = np.round( np.real(check_minues1) ,2 )
image =np.round( np.imag(check_minues1) ,2 )
real + 1j* image


array([[ 0.+0.j,  0.+0.j, -0.+0.j],
       [-0.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j, -0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j, -0.+0.j, -0.+0.j],
       [ 0.+0.j, -0.+0.j,  0.+0.j],
       [ 0.+0.j, -0.+0.j,  0.+0.j],
       [ 0.+0.j, -0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j, -0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j],
       [-0.+0.j,  0.+0.j,  0.+0.j]])

In [ ]:
D = np.eye(S.shape[0])
D[-1, -1] = 2

S_p = S + D
S_m = S - D

U_s = S_p[:, 0:p]
V_s = S_m[:, 0:p]
last_col = S_p[:, -1]

J = np.eye(m+1)[::-1]
J = J[1:,:]

UU_s = J @ U_s
VV_s = J @ V_s
joint_col = J @ last_col

eigen_veci =  np.concatenate([U_s, UU_s], axis=0)
eigen_vec_minuesi = np.concatenate([V_s, VV_s], axis=0)
new_joint = np.concatenate([last_col, joint_col], axis=0)

eigbasis_G = np.concatenate([eigvec1, eigevec_minues1, eigen_veci, new_joint[:, None], eigen_vec_minuesi], axis=1)

check = np.linalg.inv(eigbasis_G) @ G @ eigbasis_G
real = np.round( np.real(check) ,2 )
image =np.round( np.imag(check) ,2 )
real + 1j* image


array([[ 1.+0.j, -0.+0.j,  0.+0.j, -0.+0.j,  0.+0.j, -0.+0.j, -0.+0.j,
        -0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  1.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,
         0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j, -0.+0.j,  0.+0.j],
       [-0.+0.j, -0.+0.j,  1.+0.j,  0.+0.j, -0.+0.j,  0.+0.j,  0.+0.j,
         0.+0.j, -0.+0.j, -0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
       [-0.+0.j,  0.+0.j,  0.+0.j, -1.+0.j,  0.+0.j, -0.+0.j,  0.+0.j,
        -0.+0.j, -0.+0.j,  0.+0.j,  0.+0.j, -0.+0.j,  0.+0.j],
       [-0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j, -1.+0.j, -0.+0.j,  0.+0.j,
         0.+0.j, -0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
       [-0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j, -1.+0.j,  0.+0.j,
         0.+0.j, -0.+0.j,  0.+0.j,  0.+0.j, -0.+0.j,  0.+0.j],
       [-0.+0.j,  0.+0.j, -0.+0.j,  0.+0.j, -0.+0.j,  0.+0.j,  0.-1.j,
         0.+0.j,  0.+0.j,  0.+0.j, -0.+0.j,  0.+0.j, -0.+0.j],
       [ 0.+0.j, -0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j, 

In [51]:
entries =  np.array([1 if i % 2 == 0 else -1 for i in range(N)])
D = np.diag(entries)

T =  np.zeros((N,N))
T[0,-1]=1
T[1: , :-1] = np.eye(N-1)

eigvec_GtoF = np.linalg.matrix_power(T , m+1) @ D @ eigbasis_G

check = np.linalg.inv(eigvec_GtoF) @ F @ eigvec_GtoF
real = np.round( np.real(check) ,2 )
image =np.round( np.imag(check) ,2 )
real + 1j* image

T @ np.transpose(T)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [61]:
q = N //2

Tq =np.linalg.matrix_power(T, q)
Tq_inv =  np.transpose(Tq)

eig_centered = np.linalg.matrix_power(T, q) @ eigvec_GtoF
centered_fourier  = Tq @ F @ Tq_inv

check = np.linalg.matrix_power( centered_fourier,4)
real = np.round( np.real(check) ,2 )
image =np.round( np.imag(check) ,2 )
real + 1j* image

check = np.linalg.inv(eig_centered) @ centered_fourier @ eig_centered
real = np.round( np.real(check) ,2 )
image =np.round( np.imag(check) ,2 )
real + 1j* image

array([[ 0.+1.j,  0.+0.j, -0.+0.j, -0.+0.j,  0.+0.j, -0.+0.j,  0.+0.j,
         0.+0.j, -0.+0.j, -0.+0.j, -0.+0.j, -0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+1.j,  0.+0.j, -0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,
        -0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
       [-0.+0.j, -0.+0.j,  0.+1.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,
        -0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j, -0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j,  0.-1.j, -0.+0.j, -0.+0.j,  0.+0.j,
         0.+0.j,  0.+0.j, -0.+0.j,  0.+0.j, -0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.-1.j,  0.+0.j,  0.+0.j,
         0.+0.j,  0.+0.j, -0.+0.j,  0.+0.j, -0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j, -0.+0.j,  0.-1.j,  0.+0.j,
         0.+0.j,  0.+0.j, -0.+0.j,  0.+0.j, -0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j, -0.+0.j,  0.+0.j,  1.+0.j,
         0.+0.j,  0.+0.j,  0.+0.j, -0.+0.j, -0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j, -0.+0.j, -0.+0.j, 